### PR TITLE
Added stubbed functions/properties listing

### PR DESCRIPTION
**Pull request by rpedretti**
Added the ability to clear all the stubbed functions call count

### CODE REVIEW

**Comment by chuanqisun** [comment]
Hi @rpedretti, thanks for the pull request! Based on the change, it looks like you want a quick and easy way to reset the call histories on all the spied functions. I think instead of adding the `clearFunctionsCalls` method on the mocked object, a better way to do that is clearing each method manually. This way you only clear the functions that you know should be cleared.
```
it('some spec name', () => {
  /* do something */
  mockedInstance._spy.method1._func.calls.reset();
  mockedInstance._spy.method2._func.calls.reset();
  mockedInstance._spy.method3._func.calls.reset();
  /* do something else */
});
```
One goal of jasmine-mock-factory is to keep the spied object as simple as possible. It should only expose the spies without adding to or modifying what jasmine offers out-of-the-box. This way, we get two benefits: (1) the user has a single source of truth--the official jasmine documentation--when they want to manipulate the spies. (2) jasmine-mock-factory is decoupled from the jasmine API. e.g., if jasmine decides to change `calls.reset()` to `calls.clear()` in the future, jasmine-mock-factory will not break.

On another note, if you need to reset the spies in the middle of a spec, I would recommend breaking the spec into multiple smaller specs so each spec has a clean spy to start with and focuses on one thing only. This will improve the robustness of your test as well.

Finally, if you really want a util function that clears all the spies, you can write a separate helper out side of jasmine-mock-factory. Just use that helper to iterate all the method names on `mockedInstance._spy` and clear the calls. I think it's better to compose multiple functionalities than to load all of them on one object. Just let me know if you want some help exploring this route. 

Thanks again for contributing!!

**Comment by rpedretti** [comment]
Thanks on the review! My idea was to have a simple way to reset the mock without the overhead of calling _create_ before each test. I tried to create a generic function to call clear on all stubbed functions but since _spy_ is a Proxy, I can't get hands on the properties without _ownKeys_.

Is it okay to do that on the __spy_ proxy? It won't add any dependency.

Thanks in advace!

(BTW, great lib, helps a lot)

**Comment by rpedretti** [comment]
I made a test and just adding to the _spy proxy
`,ownKeys: (target) => {
     return Object.keys(this.spy);
}
`
I can itarate over it's stubbed properties/functions with _Object.getOwnPropertyNames(mock._spy);_

**Comment by chuanqisun** [comment]
Thanks @rpedretti! I would like to learn about your use case a bit more. Could you kindly share some code snippet of how you are currently using jasmine-mock-factory? You mentioned about the
> the overhead of calling _create_ before each test

Are you calling _create_ in jasmine's `it()` block or `beforeEach()` block? Are you concerned about the overhead in performance (the tests are getting slow) or are you concerned about the overhead in the amount of code you have to write?

**Comment by rpedretti** [comment]
Ok, let's say I have a _ErrorHandleService.error()_ wich is called whenever there is an error in API calls. When testing some services I constantly check how many times this function is called. The mock is created like this
```javascript
describe('SavingsContractBusiness', () => {
    const errorHandleService= MockFactory.create(_ErrorHandleService);
    const myServiceMock = MockFactory.create(MyService);

    beforeEach(() => {
        errorHandleService._spy.error._func.calls.reset();
        myServiceMock ._spy.someFunc1._func.calls.reset();
        myServiceMock ._spy.someFunc2._func.calls.reset();
        myServiceMock ._spy.someFunc3._func.calls.reset();
    });

...
   it('some desc', () => {
      myServiceMock._spy.someFunc1._func.and.throw();
      myServiceMock._spy.someFunc2._func.and.retrunValue('my return value');
      myServiceMock._spy.someFunc3._func.and.retrunValue({ myProp: 4 });

      myClassUnderTest.doStuffWithChainedCalls();

      expect(myServiceMock.someFunc1).toHaveBeenCalledTimes(1);
      expect(myServiceMock.someFunc2).toHaveBeenCalledTimes(1);
      expect(myServiceMock.someFunc3).toHaveBeenCalledTimes(1);
      expect(errorHandleService.error).toHaveBennCalledTImes(2);
   });

   it('some other desc', () => { //this will fail if not reset      
      myServiceMock._spy.someFunc1._func.and.throw();

      myClassUnderTest.doStuff();

      expect(myServiceMock.someFunc1).toHaveBeenCalledTimes(1);
      expect(myServiceMock.someFunc2).not.toHaveBeenCalledTimes();
      expect(myServiceMock.someFunc3).not.toHaveBeenCalled();
      expect(errorHandleService.error).toHaveBennCalledTImes(1);
   });
...
}
```

If I don't reset the function call counter the test will fail.

The case is that I have a class with lots of functions that are called in almost all scenarios (monstly ngOnInit, since It's an angular project). What I don't want is to call _MockFactory.create()_ for every mock (about 9) on beforeEach() and also I don't want to call every function by hand.

With the changed I proposed i can use something like

```javascript
export function clearFunctionCalls<T>(mock: Mock<T>) {
    const stubbedProps = Object.getOwnPropertyNames(mock._spy);
    for (const propertyName of stubbedProps) {
        try {
            mock._spy[propertyName]._func.calls.reset();
        } catch (error) {
        }
    }
}
```

The readability of the test will improve and it's less error prone because I assure that the call count is reset between tests and exclude the mock from the variable list.

I'm not used to write tests a lot and have little experience on it. I might be doing things wrong, but we have classes with lots of params at contructor that are injected. So please correct me if what I say is not needed.

Thanks!

**Comment by chuanqisun** [comment]
@rpedretti, the information you provided was very helpful. I suggest moving the `MockFactory.create()` calls into the `beforeEach()` block, so you can get a clean errorHandlingService mock for every spec and there is no need to reset anything. This is the recommend unit test pattern from the [angular official website](https://angular.io/guide/testing#test-a-component). As you can see they call `fixture = TestBed.createComponent(BannerComponent);` to create a new component in the `beforeEach()` block. I personally also recommend creating dependencies (`_ErrorHandleService` and `MyService`) in the `beforeEach()` for each spec, instead of doing it once for all specs. This is the best way to have a truly identical and isolated setup for each spec, giving you better robustness when your project scales up.

It would be super helpful if you can show how you are creating the `myClassUnderTest`. Since you mentioned `ngOnInit()`, I assume your `myClassUnderTest` is an angular component created by `TestBed`. I would do something like this:
```typescript
import { Mock, MockFactory } from 'jasmine-mock-factory';

describe('SavingsContractBusiness', () => {
    let errorHandleService: Mock<_ErrorHandleService>; // this gives you all the typing
    let myServiceMock: Mock <MyService>;

    beforeEach(() => {
      /* step 1 create mock dependencies */
      errorHandleService= MockFactory.create(_ErrorHandleService);
      myServiceMock = MockFactory.create(MyService);

      /* step 2 config test bed to use mock dependencies */
      TestBed.configureTestingModule({
        declarations: [ BannerComponent ],
        providers: [
          { provide: MyService, useValue: myServiceMock },
          { provide: _ErrorHandleService, useValue: errorHandleService}
        ]
      })

      /* step 3 create the component */
      fixture = TestBed.createComponent(MyClassUnderTest);
      myClassUnderTest = fixture.componentInstance;

      /* optional step 4, trigger ngOnInit */
      fixture.detectChanges(); // instead of call it here, you can do it in individual specs
    });
  ...
  }

  ...
}
```

You can read more from the "[Test a component with a dependency](https://angular.io/guide/testing#component-with-dependency)" section in the Angular testing guide.

Also, if your specs don't care about the DOM elements, you can get faster and easier setup by avoiding the TestBed and following "[isolated unit test pattern"](https://angular.io/guide/testing#isolated-unit-tests) instead. In this pattern, you simply call `new MyClassUnderTest(mockService1, mockService2, ...)` to create the component.

Please let me know if this meets your need. I was fairly confident because my team was able to use jasmine-mock-factory on a very large Angular project. We always make sure to create brand new classUnderTest in `beforeEach()`

Thanks!

**Comment by rpedretti** [comment]
Thank you very much on your review! It will surely help me a lot! I'll get a better reading at the angular docs to better understand the patterns and techniques to use at my project.

Again, thank you for your time and patience and happy holidays!

**Comment by chuanqisun** [comment]
You are very welcome! Thank you again for being part of the open source community and have a great holiday!

**Pull request closed without merging**
